### PR TITLE
CopyWith functionality for Avataaar

### PR DESCRIPTION
**Pull request by flowhorn**
This gives the ability to edit the avataaar easily on the device

### CODE REVIEW

**Comment by tomwyr** [comment]
I think you accidentally used wrong default values for the constructor (e.g. `Top.random` instead of `this.top` etc.).

**Comment by flowhorn** [comment]
No, this is intentional. It uses the value of the copy parameter or otherwise the value of the class. Try it out😃

**Comment by flowhorn** [comment]
Yes. I somehow overlooked this. It's fixed now.

**Comment by tomwyr** [comment]
I was really confused for a moment. 😃  Thanks for the PR.

**Pull request merged**
